### PR TITLE
Transcode from volute/cgiprint to github/ivoatex

### PR DESCRIPTION
**Pull request by mbtaylor**
This PR represents the basic conversion of the volute version of VOTable (in which versions 1.3 and 1.4 were authored) to an ivoatex-based build.  The volute history was imported into github, and the build machinery was updated to use the ivoatex-standard TtH-based HTML generation rather than the custom CGIPRINT converter used previously.  Most lines of the volute LaTeX source are unchanged from the original, and I've done fairly careful checking that the content in the PDF/HTML output matches what was there in the published [VOTable 1.4](http://www.ivoa.net/documents/VOTable/20191021/).

At this tag, the following changes have been made (see commit messages for details):
*  bibliography and internal references have been changed so they work in the standard way
* the architecture diagram has been replaced
* TtH has been adopted so that the HTML (and PDF) generation works correctly
* some junk has been cleared out of the latex source file
* latex fixes have been made where things were broken

Other than that, I've attempted to keep the current version looking as much like the VOTable 1.4 source/output as possible; for instance page layout is not ivoatex-standard (margins are smaller) and macros for things like XML elements may not match usage in other IVOA documents.  It is an editorial decision whether to try to homogenise VOTable in these respects.  There are also overfull hboxes (no point struggling with these now if the margins are going to change anyway).

### CODE REVIEW

**Comment by mbtaylor** [comment]
The ivoatex submodule has to get initialised.  I'm not sure what the canonical way to do that is,
but this works for me:
```
   git submodule init
   git submodule update
```
followed by
```
   make
   make biblio
   make forcetex
   make VOTable.html
```

**Comment by tomdonaldson** [comment]
OK, perfect.  That works for me too, and the content looks good.  I'll approve and merge this now.

**Comment by tomdonaldson** [comment]
I notice that with this now merged onto master, the `--recursive` arg includes the ivoatex, so this works:
```
git clone --recursive https://github.com/tomdonaldson/VOTable.git
cd VOTable
make
```

I assume that if ivoatex changes that one would still need to `git submodule update`, but that probably won't be very often.

**Comment by olebole** [comment]
The submodule is always pinned to a certain commit, and the normal `git submodule update` will revert it to that commit. To update to the latest version in the repository, one needs to issue
```
$ git submodule update --remote
$ git commit ivoatex -m "Update ivoatex to the latest commit"
$ git push
```
(ofcourse better checking that everything still works with the latest version before pushing)

**Pull request merged**
